# Generated by Django 6.0.5 on 2026-05-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Scheme categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('ministry_or_department', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('ALL', 'All India'), ('AP', 'Andhra Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('DL', 'Delhi'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], default='ALL', max_length=3)),
                ('eligibility', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='schemes.schemecategory')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
                'indexes': [models.Index(fields=['is_active', 'state'], name='schemes_sch_is_acti_bd970d_idx'), models.Index(fields=['slug'], name='schemes_sch_slug_cc65cc_idx')],
            },
        ),
    ]
