from django.core.management.base import BaseCommand

from apps.schemes.models import Scheme, SchemeCategory
from apps.scholarships.models import Scholarship


class Command(BaseCommand):
    help = "Seed realistic schemes and scholarships with official links."

    def handle(self, *args, **options):
        categories = [
            "Education",
            "Healthcare",
            "Women & Child",
            "Agriculture",
            "Employment",
            "Financial Inclusion",
            "Business & MSME",
            "Social Security",
            "Infrastructure",
        ]
        cat_map = {}
        for name in categories:
            obj, _ = SchemeCategory.objects.get_or_create(name=name)
            cat_map[name] = obj

        schemes_data = [
            {
                "title": "PMAY - Pradhan Mantri Awas Yojana",
                "category": "Infrastructure",
                "summary": "Housing support for eligible families in urban and rural India.",
                "eligibility": "Economically weaker sections, LIG/MIG groups and homeless households per PMAY norms.",
                "benefits": "Interest subsidy and housing assistance for affordable home ownership.",
                "application_url": "https://pmaymis.gov.in/",
                "tags": ["housing", "urban", "rural"],
            },
            {
                "title": "Ayushman Bharat (PM-JAY)",
                "category": "Healthcare",
                "summary": "National health protection scheme for vulnerable families.",
                "eligibility": "SECC-identified families and state-approved beneficiary categories.",
                "benefits": "Cashless secondary and tertiary hospitalization coverage.",
                "application_url": "https://pmjay.gov.in/",
                "tags": ["health", "insurance", "hospital"],
            },
            {
                "title": "PM-KISAN",
                "category": "Agriculture",
                "summary": "Direct income support for eligible landholding farmer families.",
                "eligibility": "Landholding farmer families meeting PM-KISAN criteria.",
                "benefits": "Annual income support disbursed in installments.",
                "application_url": "https://pmkisan.gov.in/",
                "tags": ["farmers", "dbt", "income-support"],
            },
            {
                "title": "Startup India",
                "category": "Business & MSME",
                "summary": "Startup recognition and ecosystem support for entrepreneurs.",
                "eligibility": "DPIIT-recognized startups meeting age and turnover limits.",
                "benefits": "Tax benefits, faster patent processing, funding support and mentoring.",
                "application_url": "https://www.startupindia.gov.in/",
                "tags": ["startup", "innovation", "entrepreneurship"],
            },
            {
                "title": "Skill India Mission",
                "category": "Employment",
                "summary": "Skill development and vocational training for youth.",
                "eligibility": "Indian youth and job seekers enrolling under approved skilling programs.",
                "benefits": "Industry-aligned skill training and certification.",
                "application_url": "https://www.skillindia.gov.in/",
                "tags": ["skill", "training", "jobs"],
            },
            {
                "title": "Stand Up India",
                "category": "Business & MSME",
                "summary": "Bank loans for SC/ST and women entrepreneurs for greenfield enterprises.",
                "eligibility": "SC/ST and women entrepreneurs above 18 years setting up new enterprises.",
                "benefits": "Institutional credit facilitation and handholding support.",
                "application_url": "https://www.standupmitra.in/",
                "tags": ["women", "sc-st", "entrepreneur"],
            },
            {
                "title": "Sukanya Samriddhi Yojana",
                "category": "Women & Child",
                "summary": "Small savings scheme for girl child financial security.",
                "eligibility": "Parents/guardians of girl child below prescribed age limit.",
                "benefits": "Attractive interest and tax benefits for long-term savings.",
                "application_url": "https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx",
                "tags": ["girl-child", "savings", "tax-benefit"],
            },
            {
                "title": "Digital India",
                "category": "Infrastructure",
                "summary": "Transform government services through digital platforms and connectivity.",
                "eligibility": "Citizens and institutions availing digital governance services.",
                "benefits": "Online service delivery, digital access and inclusion.",
                "application_url": "https://www.digitalindia.gov.in/",
                "tags": ["digital", "egovernance", "connectivity"],
            },
            {
                "title": "Pradhan Mantri Mudra Yojana",
                "category": "Business & MSME",
                "summary": "Micro-credit support for non-corporate small businesses.",
                "eligibility": "Micro and small entrepreneurs seeking non-farm business loans.",
                "benefits": "Shishu, Kishor and Tarun category collateral-free loans.",
                "application_url": "https://www.mudra.org.in/",
                "tags": ["msme", "loan", "micro-business"],
            },
            {
                "title": "Pradhan Mantri Ujjwala Yojana",
                "category": "Women & Child",
                "summary": "LPG access support for eligible poor households.",
                "eligibility": "Eligible women beneficiaries from poor households as notified.",
                "benefits": "Deposit-free LPG connection support for cleaner cooking fuel.",
                "application_url": "https://www.pmuy.gov.in/",
                "tags": ["lpg", "women", "clean-energy"],
            },
            {
                "title": "Atal Pension Yojana",
                "category": "Social Security",
                "summary": "Defined pension scheme for workers in the unorganized sector.",
                "eligibility": "Citizens aged 18-40 with bank account and contribution capacity.",
                "benefits": "Guaranteed pension amount based on contribution slab.",
                "application_url": "https://www.npscra.nsdl.co.in/scheme-details.php",
                "tags": ["pension", "retirement", "unorganized-sector"],
            },
            {
                "title": "Pradhan Mantri Jan Dhan Yojana",
                "category": "Financial Inclusion",
                "summary": "Universal access to banking, insurance and financial services.",
                "eligibility": "Any Indian citizen eligible to open a basic savings bank account.",
                "benefits": "Zero-balance bank account, RuPay card and financial inclusion features.",
                "application_url": "https://pmjdy.gov.in/",
                "tags": ["banking", "financial-inclusion", "rupay"],
            },
            {
                "title": "PM Vishwakarma",
                "category": "Employment",
                "summary": "Support package for traditional artisans and craftspeople.",
                "eligibility": "Artisans/craftspeople from recognized traditional trades.",
                "benefits": "Skill training, toolkit incentive and concessional credit.",
                "application_url": "https://pmvishwakarma.gov.in/",
                "tags": ["artisan", "skill", "credit"],
            },
            {
                "title": "PM Surya Ghar: Muft Bijli Yojana",
                "category": "Infrastructure",
                "summary": "Rooftop solar subsidy for households.",
                "eligibility": "Residential consumers with eligible rooftops and DISCOM connection.",
                "benefits": "Subsidy support for rooftop solar installations.",
                "application_url": "https://pmsuryaghar.gov.in/",
                "tags": ["solar", "subsidy", "electricity"],
            },
            {
                "title": "Lakhpati Didi Initiative",
                "category": "Women & Child",
                "summary": "Livelihood and income enhancement for women SHG members.",
                "eligibility": "Women associated with self-help groups under NRLM-linked ecosystem.",
                "benefits": "Capacity building, credit linkage and market support.",
                "application_url": "https://nrlm.gov.in/",
                "tags": ["women", "shg", "livelihood"],
            },
            {
                "title": "PM SVANidhi",
                "category": "Business & MSME",
                "summary": "Working capital loans for street vendors.",
                "eligibility": "Urban street vendors identified under scheme guidelines.",
                "benefits": "Collateral-free loans with incentive for digital transactions.",
                "application_url": "https://pmsvanidhi.mohua.gov.in/",
                "tags": ["street-vendors", "loan", "urban"],
            },
            {
                "title": "PMEGP - Prime Minister's Employment Generation Programme",
                "category": "Employment",
                "summary": "Credit-linked subsidy for micro-enterprise setup.",
                "eligibility": "Individuals and institutions starting eligible micro-enterprises.",
                "benefits": "Subsidy support on project cost through linked bank finance.",
                "application_url": "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
                "tags": ["employment", "micro-enterprise", "subsidy"],
            },
            {
                "title": "National Apprenticeship Promotion Scheme",
                "category": "Employment",
                "summary": "Apprenticeship promotion for on-the-job industry training.",
                "eligibility": "Youth and establishments participating in approved apprenticeship framework.",
                "benefits": "Stipend support and practical industry skill development.",
                "application_url": "https://www.apprenticeshipindia.gov.in/",
                "tags": ["apprenticeship", "training", "industry"],
            },
        ]

        scholarships_data = [
            {
                "title": "National Scholarship Portal (NSP)",
                "category": "National Portal",
                "provider": "Government of India",
                "level": "School/UG/PG",
                "summary": "Single-window platform for central and state scholarship applications.",
                "description": "Applicants can discover, apply for and track multiple scholarship schemes through one portal.",
                "eligibility": "Varies by scholarship listed on NSP; students must meet scheme-specific conditions.",
                "amount": "Varies by scheme",
                "deadline": None,
                "application_url": "https://scholarships.gov.in/",
                "tags": ["nsp", "central", "multi-scheme"],
            },
            {
                "title": "AICTE Pragati Scholarship for Girls",
                "category": "Technical Education",
                "provider": "AICTE",
                "level": "Diploma/UG",
                "summary": "Scholarship support for girl students in technical education.",
                "description": "Promotes girls' enrollment in AICTE-approved institutions.",
                "eligibility": "Girl students admitted to first year or second year (lateral entry) in technical courses as per AICTE norms.",
                "amount": "As per AICTE notification",
                "deadline": None,
                "application_url": "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
                "tags": ["girls", "technical", "aicte"],
            },
            {
                "title": "AICTE Saksham Scholarship",
                "category": "Technical Education",
                "provider": "AICTE",
                "level": "Diploma/UG",
                "summary": "Support for specially-abled students pursuing technical education.",
                "description": "Helps students with disabilities continue higher technical studies.",
                "eligibility": "Differently-abled students in AICTE-approved technical institutes per official criteria.",
                "amount": "As per AICTE notification",
                "deadline": None,
                "application_url": "https://www.aicte-india.org/schemes/students-development-schemes/Saksham",
                "tags": ["disability", "technical", "aicte"],
            },
            {
                "title": "INSPIRE Scholarship for Higher Education (SHE)",
                "category": "Science",
                "provider": "Department of Science and Technology (DST)",
                "level": "UG/PG",
                "summary": "Merit scholarship for students in natural and basic sciences.",
                "description": "Encourages high-performing students to pursue science education and research.",
                "eligibility": "Meritorious students in approved basic and natural science programs as per DST criteria.",
                "amount": "As per DST norms",
                "deadline": None,
                "application_url": "https://online-inspire.gov.in/",
                "tags": ["science", "dst", "merit"],
            },
            {
                "title": "AICTE Swanath Scholarship",
                "category": "Technical Education",
                "provider": "AICTE",
                "level": "Diploma/UG",
                "summary": "Scholarship for students in special hardship categories.",
                "description": "Supports orphans, children of armed forces personnel martyred in action, and students affected by COVID-19.",
                "eligibility": "Students from notified categories admitted in AICTE-approved institutions.",
                "amount": "As per AICTE notification",
                "deadline": None,
                "application_url": "https://www.aicte-india.org/schemes/students-development-schemes/Swanath",
                "tags": ["hardship", "aicte", "support"],
            },
            {
                "title": "AICTE PG Scholarship (GATE/GPAT)",
                "category": "Technical Education",
                "provider": "AICTE",
                "level": "PG",
                "summary": "Monthly scholarship for eligible GATE/GPAT-qualified PG students.",
                "description": "Financial support for AICTE-approved postgraduate technical education.",
                "eligibility": "Students admitted in AICTE-approved PG programs with valid GATE/GPAT qualifications as applicable.",
                "amount": "As per AICTE norms",
                "deadline": None,
                "application_url": "https://www.aicte-india.org/bureaus/administration/scholarship-schemes",
                "tags": ["pg", "gate", "gpat"],
            },
            {
                "title": "Post Matric Scholarship for SC Students",
                "category": "Social Justice",
                "provider": "Department of Social Justice and Empowerment",
                "level": "UG/PG",
                "summary": "Post-matric financial support for Scheduled Caste students.",
                "description": "Covers maintenance allowance and other admissible study expenses under official guidelines.",
                "eligibility": "SC students pursuing post-matric studies and meeting income/academic norms.",
                "amount": "As per official rates",
                "deadline": None,
                "application_url": "https://socialjustice.gov.in/schemes/25",
                "tags": ["sc", "post-matric", "social-justice"],
            },
            {
                "title": "Merit Cum Means Scholarship for Professional and Technical Courses (CS)",
                "category": "Minority",
                "provider": "Ministry of Minority Affairs",
                "level": "UG/PG/Professional",
                "summary": "Scholarship for minority students pursuing professional and technical courses.",
                "description": "Supports tuition and maintenance for eligible minority community students.",
                "eligibility": "Minority students with required academic performance and family income criteria.",
                "amount": "As per Ministry norms",
                "deadline": None,
                "application_url": "https://minorityaffairs.gov.in/en/schemesperformance/merit-cum-means-based-scholarships",
                "tags": ["minority", "merit-cum-means", "professional"],
            },
            {
                "title": "Central Sector Scheme of Scholarship for College and University Students",
                "category": "Merit",
                "provider": "Department of Higher Education",
                "level": "UG/PG",
                "summary": "Merit-based scholarships for top-performing students after Class 12.",
                "description": "Supports higher education continuity for meritorious students from recognized boards.",
                "eligibility": "Students above prescribed percentile in Class 12 board exams and enrolled in regular degree courses.",
                "amount": "As per scheme notification",
                "deadline": None,
                "application_url": "https://www.education.gov.in/scholarships-education-loan-4",
                "tags": ["csss", "college", "merit"],
            },
            {
                "title": "PM Scholarship Scheme for CAPF and Assam Rifles",
                "category": "Defence Personnel Families",
                "provider": "Kendriya Sainik Board",
                "level": "UG/Professional",
                "summary": "Support for wards and widows of CAPF and Assam Rifles personnel.",
                "description": "Helps beneficiaries pursue professional and technical degree courses.",
                "eligibility": "Wards/widows of eligible personnel as per KSB PMSS norms.",
                "amount": "As per PMSS rates",
                "deadline": None,
                "application_url": "https://ksb.gov.in/pmss.htm",
                "tags": ["pmss", "capf", "assam-rifles"],
            },
            {
                "title": "UP Post Matric Scholarship",
                "category": "State Government Scholarships",
                "provider": "Government of Uttar Pradesh",
                "level": "UG/PG",
                "summary": "Uttar Pradesh scholarship portal for post-matric students.",
                "description": "Covers pre and post-matric scholarship workflows for eligible categories in UP.",
                "eligibility": "UP domicile students meeting class, caste/category and income conditions.",
                "amount": "As per state rates",
                "deadline": None,
                "application_url": "https://scholarship.up.gov.in/",
                "tags": ["up", "state", "post-matric"],
            },
            {
                "title": "Maharashtra MahaDBT Scholarship",
                "category": "State Government Scholarships",
                "provider": "Government of Maharashtra",
                "level": "School/UG/PG",
                "summary": "Integrated scholarship portal for multiple Maharashtra departments.",
                "description": "Unified online platform for scholarship and benefit disbursal in Maharashtra.",
                "eligibility": "Maharashtra students meeting scheme-specific educational and income criteria.",
                "amount": "Varies by department",
                "deadline": None,
                "application_url": "https://mahadbt.maharashtra.gov.in/",
                "tags": ["maharashtra", "mahadbt", "state"],
            },
            {
                "title": "Madhya Pradesh Scholarship Portal",
                "category": "State Government Scholarships",
                "provider": "Government of Madhya Pradesh",
                "level": "School/UG/PG",
                "summary": "Scholarship management portal for MP students.",
                "description": "Provides online application and tracking for multiple MP scholarship schemes.",
                "eligibility": "MP students satisfying applicable scholarship rules.",
                "amount": "Varies",
                "deadline": None,
                "application_url": "https://scholarshipportal.mp.nic.in/",
                "tags": ["mp", "state", "portal"],
            },
            {
                "title": "Bihar Post Matric Scholarship",
                "category": "State Government Scholarships",
                "provider": "Government of Bihar",
                "level": "UG/PG",
                "summary": "Post-matric scholarship portal for Bihar students.",
                "description": "Dedicated portal for eligible reserved-category post-matric students in Bihar.",
                "eligibility": "Bihar students belonging to notified categories and meeting eligibility conditions.",
                "amount": "As per Bihar government rates",
                "deadline": None,
                "application_url": "https://pmsonline.bih.nic.in/",
                "tags": ["bihar", "post-matric", "state"],
            },
            {
                "title": "West Bengal Swami Vivekananda Merit-cum-Means Scholarship",
                "category": "State Government Scholarships",
                "provider": "Government of West Bengal",
                "level": "Higher Secondary/UG/PG",
                "summary": "Merit-cum-means scholarship for West Bengal students.",
                "description": "Provides financial aid to meritorious students from economically weaker backgrounds.",
                "eligibility": "West Bengal domicile students with required marks and income ceiling.",
                "amount": "As per SVMCM norms",
                "deadline": None,
                "application_url": "https://svmcm.wb.gov.in/",
                "tags": ["west-bengal", "svmcm", "merit-cum-means"],
            },
            {
                "title": "Karnataka State Scholarship Portal (SSP)",
                "category": "State Government Scholarships",
                "provider": "Government of Karnataka",
                "level": "School/UG/PG",
                "summary": "Single scholarship portal for Karnataka departments.",
                "description": "Students can apply for various pre- and post-matric scholarships through SSP.",
                "eligibility": "Karnataka students satisfying caste/category, income and academic norms of selected scheme.",
                "amount": "Varies by scheme",
                "deadline": None,
                "application_url": "https://ssp.karnataka.gov.in/",
                "tags": ["karnataka", "ssp", "state"],
            },
            {
                "title": "Odisha State Scholarship Portal",
                "category": "State Government Scholarships",
                "provider": "Government of Odisha",
                "level": "School/UG/PG",
                "summary": "Portal for Odisha scholarships across departments.",
                "description": "Unified application platform for pre-matric, post-matric and merit scholarships in Odisha.",
                "eligibility": "Odisha domicile students meeting scheme-level requirements.",
                "amount": "Varies by scheme",
                "deadline": None,
                "application_url": "https://scholarship.odisha.gov.in/",
                "tags": ["odisha", "state", "portal"],
            },
            {
                "title": "Digital Gujarat Scholarship",
                "category": "State Government Scholarships",
                "provider": "Government of Gujarat",
                "level": "School/UG/PG",
                "summary": "Digital application portal for Gujarat scholarships.",
                "description": "Students can apply to multiple state scholarships through Digital Gujarat.",
                "eligibility": "Gujarat domicile students with eligibility as per selected scheme.",
                "amount": "Varies",
                "deadline": None,
                "application_url": "https://www.digitalgujarat.gov.in/",
                "tags": ["gujarat", "digital-gujarat", "state"],
            },
        ]

        for item in schemes_data:
            Scheme.objects.update_or_create(
                title=item["title"],
                defaults={
                    "category": cat_map[item["category"]],
                    "summary": item["summary"],
                    "state": Scheme.State.ALL_INDIA,
                    "eligibility": item["eligibility"],
                    "benefits": item["benefits"],
                    "application_url": item["application_url"],
                    "tags": item["tags"],
                    "is_active": True,
                },
            )
        Scheme.objects.exclude(title__in=[item["title"] for item in schemes_data]).update(is_active=False)

        for item in scholarships_data:
            Scholarship.objects.update_or_create(
                title=item["title"],
                defaults={
                    "category": item["category"],
                    "provider": item["provider"],
                    "level": item["level"],
                    "summary": item["summary"],
                    "description": item["description"],
                    "eligibility": item["eligibility"],
                    "amount": item["amount"],
                    "deadline": item["deadline"],
                    "application_url": item["application_url"],
                    "tags": item["tags"],
                    "is_active": True,
                },
            )
        Scholarship.objects.exclude(title__in=[item["title"] for item in scholarships_data]).update(is_active=False)

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {len(schemes_data)} schemes and {len(scholarships_data)} scholarships successfully."
            )
        )

