# Generated by Django 6.0.5 on 2026-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=120)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('amount', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
                'indexes': [models.Index(fields=['is_active'], name='scholarship_is_acti_62e7cf_idx'), models.Index(fields=['slug'], name='scholarship_slug_4810e4_idx'), models.Index(fields=['deadline'], name='scholarship_deadlin_f24616_idx')],
            },
        ),
    ]
