# Generated by Django 6.0.5 on 2026-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(default='external', max_length=60)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_featured', 'created_at'], name='jobs_savedj_is_feat_1c082a_idx'), models.Index(fields=['external_id'], name='jobs_savedj_externa_e172d2_idx')],
            },
        ),
    ]
